
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start docker containers
      run: docker-compose up --build -d rabbitmq

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      env:
        CI: true
        NODE_ENV: "test"

    - name: Run Tests
      run: yarn test
      env:
        NODE_ENV: "test"
        CI: true